-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.InputObject exposing (..)

import Api.Enum.Direction
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


buildCoordinateInput :
    CoordinateInputRequiredFields
    -> CoordinateInput
buildCoordinateInput required____ =
    { x = required____.x, y = required____.y }


type alias CoordinateInputRequiredFields =
    { x : Int
    , y : Int
    }


{-| Type for the CoordinateInput input object.
-}
type alias CoordinateInput =
    { x : Int
    , y : Int
    }


{-| Encode a CoordinateInput into a value that can be used as an argument.
-}
encodeCoordinateInput : CoordinateInput -> Value
encodeCoordinateInput input____ =
    Encode.maybeObject
        [ ( "x", Encode.int input____.x |> Just ), ( "y", Encode.int input____.y |> Just ) ]


buildMoveOrderInput :
    MoveOrderInputRequiredFields
    -> (MoveOrderInputOptionalFields -> MoveOrderInputOptionalFields)
    -> MoveOrderInput
buildMoveOrderInput required____ fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { direction = Absent, unloads = Absent }
    in
    { unitId = required____.unitId, path = required____.path, direction = optionals____.direction, unloads = optionals____.unloads }


type alias MoveOrderInputRequiredFields =
    { unitId : String
    , path : List CoordinateInput
    }


type alias MoveOrderInputOptionalFields =
    { direction : OptionalArgument Api.Enum.Direction.Direction
    , unloads : OptionalArgument (List UnloadOrderInput)
    }


{-| Type for the MoveOrderInput input object.
-}
type alias MoveOrderInput =
    { unitId : String
    , path : List CoordinateInput
    , direction : OptionalArgument Api.Enum.Direction.Direction
    , unloads : OptionalArgument (List UnloadOrderInput)
    }


{-| Encode a MoveOrderInput into a value that can be used as an argument.
-}
encodeMoveOrderInput : MoveOrderInput -> Value
encodeMoveOrderInput input____ =
    Encode.maybeObject
        [ ( "unitId", Encode.string input____.unitId |> Just ), ( "path", (encodeCoordinateInput |> Encode.list) input____.path |> Just ), ( "direction", Encode.enum Api.Enum.Direction.toString |> Encode.optional input____.direction ), ( "unloads", (encodeUnloadOrderInput |> Encode.list) |> Encode.optional input____.unloads ) ]


buildUnloadOrderInput :
    UnloadOrderInputRequiredFields
    -> UnloadOrderInput
buildUnloadOrderInput required____ =
    { unitId = required____.unitId, destination = required____.destination }


type alias UnloadOrderInputRequiredFields =
    { unitId : String
    , destination : CoordinateInput
    }


{-| Type for the UnloadOrderInput input object.
-}
type alias UnloadOrderInput =
    { unitId : String
    , destination : CoordinateInput
    }


{-| Encode a UnloadOrderInput into a value that can be used as an argument.
-}
encodeUnloadOrderInput : UnloadOrderInput -> Value
encodeUnloadOrderInput input____ =
    Encode.maybeObject
        [ ( "unitId", Encode.string input____.unitId |> Just ), ( "destination", encodeCoordinateInput input____.destination |> Just ) ]
