-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (..)

import Api.Enum.MapType
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreateLobbyRequiredArguments =
    { name : String
    , lobbyName : String
    }


createLobby :
    CreateLobbyRequiredArguments
    -> SelectionSet decodesTo Api.Object.Snapshot
    -> SelectionSet decodesTo RootMutation
createLobby requiredArgs____ object____ =
    Object.selectionForCompositeField "createLobby" [ Argument.required "name" requiredArgs____.name Encode.string, Argument.required "lobbyName" requiredArgs____.lobbyName Encode.string ] object____ Basics.identity


type alias JoinLobbyRequiredArguments =
    { id : String
    , name : String
    }


joinLobby :
    JoinLobbyRequiredArguments
    -> SelectionSet decodesTo Api.Object.Snapshot
    -> SelectionSet decodesTo RootMutation
joinLobby requiredArgs____ object____ =
    Object.selectionForCompositeField "joinLobby" [ Argument.required "id" requiredArgs____.id Encode.string, Argument.required "name" requiredArgs____.name Encode.string ] object____ Basics.identity


type alias SetLobbyMapRequiredArguments =
    { id : String
    , mapType : Api.Enum.MapType.MapType
    }


setLobbyMap :
    SetLobbyMapRequiredArguments
    -> SelectionSet decodesTo Api.Object.Snapshot
    -> SelectionSet decodesTo RootMutation
setLobbyMap requiredArgs____ object____ =
    Object.selectionForCompositeField "setLobbyMap" [ Argument.required "id" requiredArgs____.id Encode.string, Argument.required "mapType" requiredArgs____.mapType (Encode.enum Api.Enum.MapType.toString) ] object____ Basics.identity


type alias SubmitTurnRequiredArguments =
    { id : String
    , turnNumber : Int
    , orders : List Api.InputObject.MoveOrderInput
    }


submitTurn :
    SubmitTurnRequiredArguments
    -> SelectionSet decodesTo Api.Object.GameSnapshot
    -> SelectionSet decodesTo RootMutation
submitTurn requiredArgs____ object____ =
    Object.selectionForCompositeField "submitTurn" [ Argument.required "id" requiredArgs____.id Encode.string, Argument.required "turnNumber" requiredArgs____.turnNumber Encode.int, Argument.required "orders" requiredArgs____.orders (Api.InputObject.encodeMoveOrderInput |> Encode.list) ] object____ Basics.identity


type alias StartGameRequiredArguments =
    { id : String }


startGame :
    StartGameRequiredArguments
    -> SelectionSet decodesTo Api.Object.Snapshot
    -> SelectionSet decodesTo RootMutation
startGame requiredArgs____ object____ =
    Object.selectionForCompositeField "startGame" [ Argument.required "id" requiredArgs____.id Encode.string ] object____ Basics.identity
