-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Aboard
    = Aboard


type Coordinate
    = Coordinate


type Depot
    = Depot


type Fuel
    = Fuel


type GamePlayerView
    = GamePlayerView


type GameSnapshot
    = GameSnapshot


type HitPoints
    = HitPoints


type Map
    = Map


type MovementRule
    = MovementRule


type OnMap
    = OnMap


type PlayerView
    = PlayerView


type Scenario
    = Scenario


type Snapshot
    = Snapshot


type Supplies
    = Supplies


type TerrainFeature
    = TerrainFeature


type TerrainMovementCost
    = TerrainMovementCost


type TurnEvent
    = TurnEvent


type TurnResolution
    = TurnResolution


type Unit
    = Unit
