-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Coordinate
    = Coordinate


type Depot
    = Depot


type GamePlayerView
    = GamePlayerView


type GameSnapshot
    = GameSnapshot


type Map
    = Map


type MovementRule
    = MovementRule


type PlayerView
    = PlayerView


type Scenario
    = Scenario


type Snapshot
    = Snapshot


type TerrainFeature
    = TerrainFeature


type TerrainMovementCost
    = TerrainMovementCost


type Unit
    = Unit
