-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Query exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


health : SelectionSet Bool RootQuery
health =
    Object.selectionForField "Bool" "health" [] Decode.bool


type alias LobbyRequiredArguments =
    { id : String }


lobby :
    LobbyRequiredArguments
    -> SelectionSet decodesTo Api.Object.Snapshot
    -> SelectionSet decodesTo RootQuery
lobby requiredArgs____ object____ =
    Object.selectionForCompositeField "lobby" [ Argument.required "id" requiredArgs____.id Encode.string ] object____ Basics.identity


type alias GameRequiredArguments =
    { id : String }


game :
    GameRequiredArguments
    -> SelectionSet decodesTo Api.Object.GameSnapshot
    -> SelectionSet decodesTo RootQuery
game requiredArgs____ object____ =
    Object.selectionForCompositeField "game" [ Argument.required "id" requiredArgs____.id Encode.string ] object____ Basics.identity
