-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Depot exposing (..)

import Api.Enum.Side
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


position :
    SelectionSet decodesTo Api.Object.Coordinate
    -> SelectionSet decodesTo Api.Object.Depot
position object____ =
    Object.selectionForCompositeField "position" [] object____ Basics.identity


owner : SelectionSet (Maybe Api.Enum.Side.Side) Api.Object.Depot
owner =
    Object.selectionForField "(Maybe Enum.Side.Side)" "owner" [] (Api.Enum.Side.decoder |> Decode.nullable)
