-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.GameSnapshot exposing (..)

import Api.Enum.MapType
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet String Api.Object.GameSnapshot
id =
    Object.selectionForField "String" "id" [] Decode.string


name : SelectionSet String Api.Object.GameSnapshot
name =
    Object.selectionForField "String" "name" [] Decode.string


mapType : SelectionSet Api.Enum.MapType.MapType Api.Object.GameSnapshot
mapType =
    Object.selectionForField "Enum.MapType.MapType" "mapType" [] Api.Enum.MapType.decoder


players :
    SelectionSet decodesTo Api.Object.GamePlayerView
    -> SelectionSet (List decodesTo) Api.Object.GameSnapshot
players object____ =
    Object.selectionForCompositeField "players" [] object____ (Basics.identity >> Decode.list)


isHost : SelectionSet Bool Api.Object.GameSnapshot
isHost =
    Object.selectionForField "Bool" "isHost" [] Decode.bool


isMember : SelectionSet Bool Api.Object.GameSnapshot
isMember =
    Object.selectionForField "Bool" "isMember" [] Decode.bool


gameUrl : SelectionSet (Maybe String) Api.Object.GameSnapshot
gameUrl =
    Object.selectionForField "(Maybe String)" "gameUrl" [] (Decode.string |> Decode.nullable)


scenario :
    SelectionSet decodesTo Api.Object.Scenario
    -> SelectionSet decodesTo Api.Object.GameSnapshot
scenario object____ =
    Object.selectionForCompositeField "scenario" [] object____ Basics.identity
