-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.GamePlayerView exposing (..)

import Api.Enum.Side
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


name : SelectionSet String Api.Object.GamePlayerView
name =
    Object.selectionForField "String" "name" [] Decode.string


isHost : SelectionSet Bool Api.Object.GamePlayerView
isHost =
    Object.selectionForField "Bool" "isHost" [] Decode.bool


isYou : SelectionSet Bool Api.Object.GamePlayerView
isYou =
    Object.selectionForField "Bool" "isYou" [] Decode.bool


side : SelectionSet Api.Enum.Side.Side Api.Object.GamePlayerView
side =
    Object.selectionForField "Enum.Side.Side" "side" [] Api.Enum.Side.decoder
