-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Map exposing (..)

import Api.Enum.MapTheme
import Api.Enum.Terrain
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


width : SelectionSet Int Api.Object.Map
width =
    Object.selectionForField "Int" "width" [] Decode.int


height : SelectionSet Int Api.Object.Map
height =
    Object.selectionForField "Int" "height" [] Decode.int


theme : SelectionSet Api.Enum.MapTheme.MapTheme Api.Object.Map
theme =
    Object.selectionForField "Enum.MapTheme.MapTheme" "theme" [] Api.Enum.MapTheme.decoder


baseTile : SelectionSet Api.Enum.Terrain.Terrain Api.Object.Map
baseTile =
    Object.selectionForField "Enum.Terrain.Terrain" "baseTile" [] Api.Enum.Terrain.decoder


features :
    SelectionSet decodesTo Api.Object.TerrainFeature
    -> SelectionSet (List decodesTo) Api.Object.Map
features object____ =
    Object.selectionForCompositeField "features" [] object____ (Basics.identity >> Decode.list)
