-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Scenario exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


map :
    SelectionSet decodesTo Api.Object.Map
    -> SelectionSet decodesTo Api.Object.Scenario
map object____ =
    Object.selectionForCompositeField "map" [] object____ Basics.identity


depots :
    SelectionSet decodesTo Api.Object.Depot
    -> SelectionSet (List decodesTo) Api.Object.Scenario
depots object____ =
    Object.selectionForCompositeField "depots" [] object____ (Basics.identity >> Decode.list)


units :
    SelectionSet decodesTo Api.Object.Unit
    -> SelectionSet (List decodesTo) Api.Object.Scenario
units object____ =
    Object.selectionForCompositeField "units" [] object____ (Basics.identity >> Decode.list)
