-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.TerrainMovementCost exposing (..)

import Api.Enum.Terrain
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


terrain : SelectionSet Api.Enum.Terrain.Terrain Api.Object.TerrainMovementCost
terrain =
    Object.selectionForField "Enum.Terrain.Terrain" "terrain" [] Api.Enum.Terrain.decoder


cost : SelectionSet Int Api.Object.TerrainMovementCost
cost =
    Object.selectionForField "Int" "cost" [] Decode.int
