-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.TurnEvent exposing (..)

import Api.Enum.Direction
import Api.Enum.TurnEventKind
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


initialDirection : SelectionSet Api.Enum.Direction.Direction Api.Object.TurnEvent
initialDirection =
    Object.selectionForField "Enum.Direction.Direction" "initialDirection" [] Api.Enum.Direction.decoder


kind : SelectionSet Api.Enum.TurnEventKind.TurnEventKind Api.Object.TurnEvent
kind =
    Object.selectionForField "Enum.TurnEventKind.TurnEventKind" "kind" [] Api.Enum.TurnEventKind.decoder


unitId : SelectionSet String Api.Object.TurnEvent
unitId =
    Object.selectionForField "String" "unitId" [] Decode.string


path :
    SelectionSet decodesTo Api.Object.Coordinate
    -> SelectionSet (List decodesTo) Api.Object.TurnEvent
path object____ =
    Object.selectionForCompositeField "path" [] object____ (Basics.identity >> Decode.list)
