-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.TurnResolution exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


turnNumber : SelectionSet Int Api.Object.TurnResolution
turnNumber =
    Object.selectionForField "Int" "turnNumber" [] Decode.int


events :
    SelectionSet decodesTo Api.Object.TurnEvent
    -> SelectionSet (List decodesTo) Api.Object.TurnResolution
events object____ =
    Object.selectionForCompositeField "events" [] object____ (Basics.identity >> Decode.list)


{-| Viewer-specific frames are populated when visibility projects the resolution.
-}
frames :
    SelectionSet decodesTo Api.Object.TurnFrame
    -> SelectionSet (List decodesTo) Api.Object.TurnResolution
frames object____ =
    Object.selectionForCompositeField "frames" [] object____ (Basics.identity >> Decode.list)
