-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.TurnFrame exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


units :
    SelectionSet decodesTo Api.Object.Unit
    -> SelectionSet (List decodesTo) Api.Object.TurnFrame
units object____ =
    Object.selectionForCompositeField "units" [] object____ (Basics.identity >> Decode.list)


visibleTiles :
    SelectionSet decodesTo Api.Object.Coordinate
    -> SelectionSet (List decodesTo) Api.Object.TurnFrame
visibleTiles object____ =
    Object.selectionForCompositeField "visibleTiles" [] object____ (Basics.identity >> Decode.list)
