-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Unit exposing (..)

import Api.Enum.Direction
import Api.Enum.Side
import Api.Enum.UnitKind
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet String Api.Object.Unit
id =
    Object.selectionForField "String" "id" [] Decode.string


side : SelectionSet Api.Enum.Side.Side Api.Object.Unit
side =
    Object.selectionForField "Enum.Side.Side" "side" [] Api.Enum.Side.decoder


kind : SelectionSet Api.Enum.UnitKind.UnitKind Api.Object.Unit
kind =
    Object.selectionForField "Enum.UnitKind.UnitKind" "kind" [] Api.Enum.UnitKind.decoder


direction : SelectionSet Api.Enum.Direction.Direction Api.Object.Unit
direction =
    Object.selectionForField "Enum.Direction.Direction" "direction" [] Api.Enum.Direction.decoder


position :
    SelectionSet decodesTo Api.Object.Coordinate
    -> SelectionSet decodesTo Api.Object.Unit
position object____ =
    Object.selectionForCompositeField "position" [] object____ Basics.identity
