-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.Direction exposing (..)

import Json.Decode as Decode exposing (Decoder)


type Direction
    = North
    | East
    | South
    | West


list : List Direction
list =
    [ North, East, South, West ]


decoder : Decoder Direction
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "NORTH" ->
                        Decode.succeed North

                    "EAST" ->
                        Decode.succeed East

                    "SOUTH" ->
                        Decode.succeed South

                    "WEST" ->
                        Decode.succeed West

                    _ ->
                        Decode.fail ("Invalid Direction type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Direction -> String
toString enum____ =
    case enum____ of
        North ->
            "NORTH"

        East ->
            "EAST"

        South ->
            "SOUTH"

        West ->
            "WEST"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Direction
fromString enumString____ =
    case enumString____ of
        "NORTH" ->
            Just North

        "EAST" ->
            Just East

        "SOUTH" ->
            Just South

        "WEST" ->
            Just West

        _ ->
            Nothing
