-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.MapTheme exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| Appearance is independent of terrain movement and visibility rules.
-}
type MapTheme
    = GreenForest
    | Desert
    | Snow


list : List MapTheme
list =
    [ GreenForest, Desert, Snow ]


decoder : Decoder MapTheme
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "GREEN_FOREST" ->
                        Decode.succeed GreenForest

                    "DESERT" ->
                        Decode.succeed Desert

                    "SNOW" ->
                        Decode.succeed Snow

                    _ ->
                        Decode.fail ("Invalid MapTheme type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : MapTheme -> String
toString enum____ =
    case enum____ of
        GreenForest ->
            "GREEN_FOREST"

        Desert ->
            "DESERT"

        Snow ->
            "SNOW"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe MapTheme
fromString enumString____ =
    case enumString____ of
        "GREEN_FOREST" ->
            Just GreenForest

        "DESERT" ->
            Just Desert

        "SNOW" ->
            Just Snow

        _ ->
            Nothing
