-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.MapType exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| A scenario selection. Board layout and rules will be implemented separately.
-}
type MapType
    = SupplyPoint


list : List MapType
list =
    [ SupplyPoint ]


decoder : Decoder MapType
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "SUPPLY_POINT" ->
                        Decode.succeed SupplyPoint

                    _ ->
                        Decode.fail ("Invalid MapType type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : MapType -> String
toString enum____ =
    case enum____ of
        SupplyPoint ->
            "SUPPLY_POINT"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe MapType
fromString enumString____ =
    case enumString____ of
        "SUPPLY_POINT" ->
            Just SupplyPoint

        _ ->
            Nothing
