-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.MapType exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| Selects the fixed initial board and forces for a game.
-}
type MapType
    = SupplyPoint
    | ElAlamein
    | BloodGulch
    | Arabia
    | Sidewinder
    | BlackForest


list : List MapType
list =
    [ SupplyPoint, ElAlamein, BloodGulch, Arabia, Sidewinder, BlackForest ]


decoder : Decoder MapType
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "SUPPLY_POINT" ->
                        Decode.succeed SupplyPoint

                    "EL_ALAMEIN" ->
                        Decode.succeed ElAlamein

                    "BLOOD_GULCH" ->
                        Decode.succeed BloodGulch

                    "ARABIA" ->
                        Decode.succeed Arabia

                    "SIDEWINDER" ->
                        Decode.succeed Sidewinder

                    "BLACK_FOREST" ->
                        Decode.succeed BlackForest

                    _ ->
                        Decode.fail ("Invalid MapType type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : MapType -> String
toString enum____ =
    case enum____ of
        SupplyPoint ->
            "SUPPLY_POINT"

        ElAlamein ->
            "EL_ALAMEIN"

        BloodGulch ->
            "BLOOD_GULCH"

        Arabia ->
            "ARABIA"

        Sidewinder ->
            "SIDEWINDER"

        BlackForest ->
            "BLACK_FOREST"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe MapType
fromString enumString____ =
    case enumString____ of
        "SUPPLY_POINT" ->
            Just SupplyPoint

        "EL_ALAMEIN" ->
            Just ElAlamein

        "BLOOD_GULCH" ->
            Just BloodGulch

        "ARABIA" ->
            Just Arabia

        "SIDEWINDER" ->
            Just Sidewinder

        "BLACK_FOREST" ->
            Just BlackForest

        _ ->
            Nothing
