-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.Side exposing (..)

import Json.Decode as Decode exposing (Decoder)


type Side
    = West
    | East


list : List Side
list =
    [ West, East ]


decoder : Decoder Side
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "WEST" ->
                        Decode.succeed West

                    "EAST" ->
                        Decode.succeed East

                    _ ->
                        Decode.fail ("Invalid Side type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Side -> String
toString enum____ =
    case enum____ of
        West ->
            "WEST"

        East ->
            "EAST"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Side
fromString enumString____ =
    case enumString____ of
        "WEST" ->
            Just West

        "EAST" ->
            Just East

        _ ->
            Nothing
