-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.Side exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| Player ownership, independent of starting position on a map.
-}
type Side
    = Player1
    | Player2


list : List Side
list =
    [ Player1, Player2 ]


decoder : Decoder Side
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "PLAYER1" ->
                        Decode.succeed Player1

                    "PLAYER2" ->
                        Decode.succeed Player2

                    _ ->
                        Decode.fail ("Invalid Side type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Side -> String
toString enum____ =
    case enum____ of
        Player1 ->
            "PLAYER1"

        Player2 ->
            "PLAYER2"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Side
fromString enumString____ =
    case enumString____ of
        "PLAYER1" ->
            Just Player1

        "PLAYER2" ->
            Just Player2

        _ ->
            Nothing
