-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.Terrain exposing (..)

import Json.Decode as Decode exposing (Decoder)


type Terrain
    = GrassPlain
    | Hills
    | Forest


list : List Terrain
list =
    [ GrassPlain, Hills, Forest ]


decoder : Decoder Terrain
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "GRASS_PLAIN" ->
                        Decode.succeed GrassPlain

                    "HILLS" ->
                        Decode.succeed Hills

                    "FOREST" ->
                        Decode.succeed Forest

                    _ ->
                        Decode.fail ("Invalid Terrain type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Terrain -> String
toString enum____ =
    case enum____ of
        GrassPlain ->
            "GRASS_PLAIN"

        Hills ->
            "HILLS"

        Forest ->
            "FOREST"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Terrain
fromString enumString____ =
    case enumString____ of
        "GRASS_PLAIN" ->
            Just GrassPlain

        "HILLS" ->
            Just Hills

        "FOREST" ->
            Just Forest

        _ ->
            Nothing
