-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.TurnEventKind exposing (..)

import Json.Decode as Decode exposing (Decoder)


type TurnEventKind
    = Move
    | Rotate
    | Load
    | Unload
    | Hold
    | DestinationConflict


list : List TurnEventKind
list =
    [ Move, Rotate, Load, Unload, Hold, DestinationConflict ]


decoder : Decoder TurnEventKind
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "MOVE" ->
                        Decode.succeed Move

                    "ROTATE" ->
                        Decode.succeed Rotate

                    "LOAD" ->
                        Decode.succeed Load

                    "UNLOAD" ->
                        Decode.succeed Unload

                    "HOLD" ->
                        Decode.succeed Hold

                    "DESTINATION_CONFLICT" ->
                        Decode.succeed DestinationConflict

                    _ ->
                        Decode.fail ("Invalid TurnEventKind type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : TurnEventKind -> String
toString enum____ =
    case enum____ of
        Move ->
            "MOVE"

        Rotate ->
            "ROTATE"

        Load ->
            "LOAD"

        Unload ->
            "UNLOAD"

        Hold ->
            "HOLD"

        DestinationConflict ->
            "DESTINATION_CONFLICT"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe TurnEventKind
fromString enumString____ =
    case enumString____ of
        "MOVE" ->
            Just Move

        "ROTATE" ->
            Just Rotate

        "LOAD" ->
            Just Load

        "UNLOAD" ->
            Just Unload

        "HOLD" ->
            Just Hold

        "DESTINATION_CONFLICT" ->
            Just DestinationConflict

        _ ->
            Nothing
