-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.UnitKind exposing (..)

import Json.Decode as Decode exposing (Decoder)


type UnitKind
    = Infantry
    | Tank
    | FieldGun
    | SupplyTruck


list : List UnitKind
list =
    [ Infantry, Tank, FieldGun, SupplyTruck ]


decoder : Decoder UnitKind
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "INFANTRY" ->
                        Decode.succeed Infantry

                    "TANK" ->
                        Decode.succeed Tank

                    "FIELD_GUN" ->
                        Decode.succeed FieldGun

                    "SUPPLY_TRUCK" ->
                        Decode.succeed SupplyTruck

                    _ ->
                        Decode.fail ("Invalid UnitKind type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : UnitKind -> String
toString enum____ =
    case enum____ of
        Infantry ->
            "INFANTRY"

        Tank ->
            "TANK"

        FieldGun ->
            "FIELD_GUN"

        SupplyTruck ->
            "SUPPLY_TRUCK"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe UnitKind
fromString enumString____ =
    case enumString____ of
        "INFANTRY" ->
            Just Infantry

        "TANK" ->
            Just Tank

        "FIELD_GUN" ->
            Just FieldGun

        "SUPPLY_TRUCK" ->
            Just SupplyTruck

        _ ->
            Nothing
